### ISSUE TITLE
cgroup1 cgrpup2

### ISSUE THREAD

**Issue by captainlee1024** [impact-eintr/Docker-ECE#5]
## 关于cgroup1 和 cgroup2

> Q: 你好。想请问一下，在其容器的时候，是怎么给cgroup1和cgroup2做兼容的呢，在起容器之前，是怎么获取到当前主机是cgroup1还是cgroup2呢？

**Comment by impact-eintr** [comment]
你好，现在的版本只支持cgroup2，需要在启动的时候手动指定。关于兼容，之后有时间我会尝试做一下，目前我还没什么解决方案，欢迎交流想法。

**Comment by impact-eintr** [comment]
``` go
 // 开启cgroup
        // 检查版本
        _, err = exec.Command("grep", "cgroup2", "/proc/filesystems").CombinedOutput()
        if err != nil {
                // cgroup 1
                cgroupManager := cgroups.NewCgroupManager("")
                if tty {
                        defer cgroupManager.Destroy()
                }
                cgroupManager.Set(res)
                cgroupManager.Apply(parent.Process.Pid)

        } else {
                // cgroup 2
                fmt.Println("cgroup2")
                cgroupManager := cgroups.NewCgroupManager(containerInit.Id_base)
                if tty {
                        defer cgroupManager.Destroy2()
                }
                cgroupManager.Set2(res)
                cgroupManager.Apply2(parent.Process.Pid)
        }

```

**Comment by impact-eintr** [comment]
> ## 关于cgroup1 和 cgroup2
> > Q: 你好。想请问一下，在其容器的时候，是怎么给cgroup1和cgroup2做兼容的呢，在起容器之前，是怎么获取到当前主机是cgroup1还是cgroup2呢？

你好，我暂时使用 `grep cgroup2 /proc/filesystems` 命令的返回结果作为判断依据 这样就不需要在启动时指定版本了，但看上去仍然没有做到兼容，我会继续关注这个问题

**Comment by captainlee1024** [comment]
> > ## 关于 cgroup1 和 cgroup2
> > > 问：你好。想请教一下，在其容器的时候，是怎么给cgroup1和cgroup2做具体的呢，在起容器之前，是怎么获取到主机当前是cgroup1还是cgroup2呢？
> 
> 你好，我暂时使用`grep cgroup2 /proc/filesystems`命令的返回结果作为判断是否就在这个时间版本，但启动看起来还没有真正的问题，我会继续关注问题

感谢大佬哈，但是现在有个问题，就是如果系统，例如我用的是manjaro 它是支持两个版本的，如果你`grep cgroup /proc/filesystems` 会发现它会找到cgroup 和 cgroup2 两个, 但这并不是系统实际运行的cgroup版本，cgourp版本可以在系统内核引导参数里指定，例如我的是在`/etc/default/grub/`里 `GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=0`来设置系统启用cgroupv1的，我在想是不是有什么环境变量可以读取到这个`systemd.unified_cgroup_hierarchy`的参数的配置，但是目前仍然没有解决。希望后续能多交流哈！

**Comment by impact-eintr** [comment]
> > > ## 关于 cgroup1 和 cgroup2
> > > > 问：你好。想请教一下，在其容器的时候，是怎么给cgroup1和cgroup2做具体的呢，在起容器之前，是怎么获取到主机当前是cgroup1还是cgroup2呢？
> > 
> > 
> > 你好，我暂时使用`grep cgroup2 /proc/filesystems`命令的返回结果作为判断是否就在这个时间版本，但启动看起来还没有真正的问题，我会继续关注问题
> 
> 感谢大佬哈，但是现在有个问题，就是如果系统，例如我用的是manjaro 它是支持两个版本的，如果你`grep cgroup /proc/filesystems` 会发现它会找到cgroup 和 cgroup2 两个，这两个应该是系统支持的列表, 但这并不是系统实际运行的cgroup版本，cgourp版本可以在系统内核引导参数里指定，例如我的是在`/etc/default/grub/`里 `GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=0`来设置系统启用cgroupv1的，我在想是不是有什么环境变量可以读取到这个`systemd.unified_cgroup_hierarchy`的参数的配置，但是目前仍然没有解决。希望后续能多交流哈！


> 

感谢你的回复，我没有尝试过在我的物理机（manjaro）上开启cgroup v1，之前的实验是在虚拟机上做的（centos7），之后我会尝试开启并继续实验，目前准备使用 mount | grep cgroup2 的结果来进行判断，希望继续交流。

**Comment by captainlee1024** [comment]
我似乎找到了解决方案：
1. 在containerd项目中
[containerd的cgroup包下](https://github.com/containerd/cgroups/blob/main/utils.go)
2. 在runc项目中
[runc的lincontainer/cgroups下](https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/utils.go)

但是我还没具体去实践，不过我觉得这应该就是解，如果有其他大型项目中有方案的话可以列出来一起学习一下😊

**Comment by impact-eintr** [comment]
> 我似乎找到了解决方案：
> 
> 1. 在containerd项目中
>    [containerd的cgroup包下](https://github.com/containerd/cgroups/blob/main/utils.go)
> 2. 在runc项目中
>    [runc的lincontainer/cgroups下](https://github.com/opencontainers/runc/blob/master/libcontainer/cgroups/utils.go)
> 
> 但是我还没具体去实践，不过我觉得这应该就是解，如果有其他大型项目中有方案的话可以列出来一起学习一下blush

感谢大佬指路👍，有时间我会尝试把这个实践一下。
