### ISSUE TITLE
sudo brctl addif br0 eth0 疑问

### ISSUE THREAD

**Issue by mqy224512** [impact-eintr/Docker-ECE#7]
请教一个问题，执行完 sudo brctl addif br0 eth0 之后机器就断网了，这个怎么解决呢

**Comment by impact-eintr** [comment]
建议还是不要挂载主网卡，做实验还是隔离环境好点，想要解除用`sudo brctl delif br0 erh0`，原书上挂载了`veth0`。原理我也不是很清楚，欢迎交流: )。

**Comment by mqy224512** [comment]
创建一个新的网卡做实验吗，大佬网络这一块环境是怎么做的

**Comment by impact-eintr** [comment]
可以，我当时记得用的是无线网卡做的，把书上面的例子运行完就去看代码去了，没刻意配环境。

**Comment by mqy224512** [comment]
好的，先继续学习
